receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 3s
          static_configs:
            - targets: [localhost:8888]        
exporters:
  logging:
    verbosity: Detailed
  prometheus:
    endpoint: "0.0.0.0:9464"  
processors:
  batch:
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [logging, prometheus]
      processors: [batch]  
